package app;

import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/ies/profesor") // This means URL's start with /demo (after Application path)
public class ProfesorController {
	@Autowired // This means to get the bean called userRepository
				// Which is auto-generated by Spring, we will use it to handle the data
	private ProfesorRepository repository;

	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private ModuloRepository mrepository;


	@GetMapping(path = "/add") // Map ONLY GET Requests
	public @ResponseBody String addNewProfe(@RequestParam String name, @RequestParam String ape1,
			@RequestParam String ape2) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		Profesor p = new Profesor();
		p.setNombre(name);
		p.setApe1(ape1);
		p.setApe2(ape2);
		p.setHorasAsignadas(0);
		repository.save(p);
		return "Saved";
	}

	@GetMapping(path = "/{id}")
	public @ResponseBody Profesor getUser(@PathVariable int id) {
		Optional<Profesor> p = repository.findById(id);
		return p.get();
	}

	@GetMapping(path = "/{id}/afegir")
	public @ResponseBody String afegirModul(@PathVariable int id, @RequestParam int modul) {
		Optional<Profesor> op = repository.findById(id);
		Optional<Modulo> om = mrepository.findById(modul);
		Profesor p = op.get();
		Modulo m = om.get();
		if (p.getHorasAsignadas() + m.getHorasSemana() > 20) {
			return "No se puede anyadir Modulo, se sobrepasan las horas asignadas";
			
		} else {
			p.getModulos().add(m);
			m.getProfesores().add(p);
			p.setHorasAsignadas(p.getHorasAsignadas() + m.getHorasSemana());
			System.out.println(repository);
			repository.save(p);
			mrepository.save(m);
			return "OK";
		}

	}

	@GetMapping(path = "/cognom/{cognom}")
	public @ResponseBody Iterable<Profesor> getAllUsers2(@PathVariable String cognom) {
		// This returns a JSON or XML with the users
		return repository.findByApe1OrderByNombreAsc(cognom);
	}

	@GetMapping(path = "/all")
	public @ResponseBody Iterable<Profesor> getAllUsers() {
		// This returns a JSON or XML with the users
		return repository.findAll();
	}
}
